### PR TITLE
Added Chinese translation

### PR DESCRIPTION
**Pull request by mowenxuan**
Added Chinese translation

### CODE REVIEW

**Comment by Achimobil** [comment]
Hi,
I do not accept languages in the description which I do not speak, because when it is in there I need to write a changelog on every update. The translation file and title will be ok when you send me only these

**Comment by mowenxuan** [comment]
Ok, I re-modified modDesc.

**Comment by Achimobil** [comment]
Thanks, I think many chinese speaking users will love that

**Comment by mowenxuan** [comment]
I changed the translation statement of modDesc.xml, changing the sixth line of <cs>更多信息扩展</cs> to <cs>信息显示扩展</cs>
[modDesc.zip](https://github.com/user-attachments/files/18141520/modDesc.zip)

**Comment by Achimobil** [comment]
I have taken the changed line

**Comment by mowenxuan** [comment]
As you thought, Chinese people are quite fond of this module.

**Pull request merged**
